-- phpMyAdmin SQL Dump
-- version 4.4.14
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: 07 Jan 2016 pada 10.37
-- Versi Server: 5.6.26
-- PHP Version: 5.6.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `genius2016`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `tbsoal`
--

CREATE TABLE IF NOT EXISTS `tbsoal` (
  `indeks` int(11) NOT NULL,
  `sesi` int(11) NOT NULL,
  `pertanyaan` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data untuk tabel `tbsoal`
--

INSERT INTO `tbsoal` (`indeks`, `sesi`, `pertanyaan`) VALUES
(1, 1, '<p><s>Apakah saya?</s></p>\r\n\r\n<table border="0" cellpadding="1" cellspacing="1" style="width:500px">\r\n	<tbody>\r\n		<tr>\r\n			<td>A. ungkapkan rasaa</td>\r\n		</tr>\r\n		<tr>\r\n			<td>B. kamu percaya</td>\r\n		</tr>\r\n		<tr>\r\n			<td>C. butuh cinta</td>\r\n		</tr>\r\n		<tr>\r\n			<td>D. merangkai kata</td>\r\n		</tr>\r\n		<tr>\r\n			<td>E. katakan cinta sekarang</td>\r\n		</tr>\r\n	</tbody>\r\n</table>\r\n\r\n<p>&nbsp;</p>\r\n'),
(2, 0, '<table align="left" border="0" cellpadding="0" cellspacing="0" style="width:100%">\r\n	<tbody>\r\n		<tr>\r\n			<td>\r\n			<p>&nbsp;</p>\r\n			</td>\r\n			<td>\r\n			<div class="default">Pada suatu kantong, terdapat 50 buah bola yang berwarna merah,kuning,putih,dan hitam. Jika tiap satu menit Riki hanya bias mengambil satu bola. Maka pada menit ke berapa Riki pasti mendapat 12 Bola berwarana sama ?</div>\r\n\r\n			<div class="default">\r\n			<table border="0" cellpadding="0" cellspacing="0" style="width:95%">\r\n				<tbody>\r\n					<tr>\r\n						<td>\r\n						<div>a</div>\r\n						</td>\r\n						<td>50</td>\r\n						<td>\r\n						<div>d</div>\r\n						</td>\r\n						<td>45</td>\r\n					</tr>\r\n					<tr>\r\n						<td>\r\n						<div>b</div>\r\n						</td>\r\n						<td>40</td>\r\n						<td>\r\n						<div>e</div>\r\n						</td>\r\n						<td>38</td>\r\n					</tr>\r\n					<tr>\r\n						<td>\r\n						<div>c</div>\r\n						</td>\r\n						<td>44</td>\r\n					</tr>\r\n				</tbody>\r\n			</table>\r\n			</div>\r\n			</td>\r\n		</tr>\r\n	</tbody>\r\n</table>\r\n'),
(3, 0, '<div class="default">Dimas memiliki 4 pasang magnet angka yang terdiri datri angka 1,2,4,5. Dia akan mengurutkan manet tersebut di kulkasnya dengan cara yang unik,yaitu :<br />\r\n~ angka 1 dipisah 1 magnet<br />\r\n~ angka 2 dipisah oleh 2 magnet<br />\r\n~ angka 4 dipisah oleh 4 magnet<br />\r\n~ angka 5 dipisah oleh 5 magnet<br />\r\n~ angka yang terbentuk adalh angka terbesat yang bias dihasilkan sesuai syarat diatas .<br />\r\nMaka magnet ke 5 dari susunan yang Dimas hasilkan jika dilihat dari kanan yaitu ? &hellip;</div>\r\n\r\n<div class="default">\r\n<table border="0" cellpadding="0" cellspacing="0" style="width:95%">\r\n	<tbody>\r\n		<tr>\r\n			<td>\r\n			<div class="choice">a.</div>\r\n			</td>\r\n			<td>1</td>\r\n			<td>\r\n			<div class="choice">d.</div>\r\n			</td>\r\n			<td>5</td>\r\n		</tr>\r\n		<tr>\r\n			<td>\r\n			<div class="choice">b.</div>\r\n			</td>\r\n			<td>2</td>\r\n			<td>\r\n			<div class="choice">e.</div>\r\n			</td>\r\n			<td>Magnet tidak dapat tersusun</td>\r\n		</tr>\r\n		<tr>\r\n			<td>\r\n			<div class="choice">c.</div>\r\n			</td>\r\n			<td>4</td>\r\n		</tr>\r\n	</tbody>\r\n</table>\r\n</div>\r\n'),
(4, 0, 'Ini gantinya nomor 4'),
(5, 0, '<p>Aji has decided he __________ arts at university</p>\r\n\r\n<table border="0" cellpadding="0" cellspacing="0">\r\n	<tbody>\r\n		<tr>\r\n			<td style="width:24px">\r\n			<p>a.</p>\r\n			</td>\r\n			<td style="width:258px">\r\n			<p>Studied</p>\r\n			</td>\r\n			<td style="width:24px">\r\n			<p>d.</p>\r\n			</td>\r\n			<td style="width:258px">\r\n			<p>will study</p>\r\n			</td>\r\n		</tr>\r\n		<tr>\r\n			<td style="width:24px">\r\n			<p>b.</p>\r\n			</td>\r\n			<td style="width:258px">\r\n			<p>Studies</p>\r\n			</td>\r\n			<td style="width:24px">\r\n			<p>e.</p>\r\n			</td>\r\n			<td style="width:258px">\r\n			<p>is going to study</p>\r\n			</td>\r\n		</tr>\r\n		<tr>\r\n			<td style="width:24px">\r\n			<p>c.</p>\r\n			</td>\r\n			<td style="width:258px">\r\n			<p>is studying</p>\r\n			</td>\r\n			<td colspan="2">\r\n			<p>&nbsp;</p>\r\n			</td>\r\n		</tr>\r\n	</tbody>\r\n</table>\r\n'),
(6, 0, '<table align="left" border="0" cellpadding="0" cellspacing="0" style="width:100%">\r\n	<tbody>\r\n		<tr>\r\n			<td>\r\n			<p>&nbsp;</p>\r\n			</td>\r\n			<td>\r\n			<div class="default">Sesaat setelah matahari terbenam, Senja melihat sebuah objek langit mirip bintang yang sangat terang di langit. Jika tidak ada objek langit lain saat itu, apa nama objek langit yang dilihat?</div>\r\n\r\n			<div class="default">\r\n			<table border="0" cellpadding="0" cellspacing="0" style="width:95%">\r\n				<tbody>\r\n					<tr>\r\n						<td>\r\n						<div class="choice">a.</div>\r\n						</td>\r\n						<td>Planet Merkurius</td>\r\n						<td>\r\n						<div class="choice">d.</div>\r\n						</td>\r\n						<td>Planet Jupiter</td>\r\n					</tr>\r\n					<tr>\r\n						<td>\r\n						<div class="choice">b.</div>\r\n						</td>\r\n						<td>Planet Kejora</td>\r\n						<td>\r\n						<div class="choice">e.</div>\r\n						</td>\r\n						<td>Jawaban diatas tidak ada yang benar</td>\r\n					</tr>\r\n					<tr>\r\n						<td>\r\n						<div class="choice">c.</div>\r\n						</td>\r\n						<td>Planet Mars</td>\r\n					</tr>\r\n				</tbody>\r\n			</table>\r\n			</div>\r\n			</td>\r\n		</tr>\r\n	</tbody>\r\n</table>\r\n'),
(7, 0, '<div class="default">Berat badan Ipun di permukaan bumi adalah 400N. Jika Ipun pergi ke suatu planet yang massanya 5 kali massa bumi dan jari-jarinya 2 kali jari-jari bumi, maka berat Ipun di permukaan planet itu adalah? &hellip;</div>\r\n\r\n<div class="default">\r\n<table border="0" cellpadding="0" cellspacing="0" style="width:95%">\r\n	<tbody>\r\n		<tr>\r\n			<td>\r\n			<div class="choice">a.</div>\r\n			</td>\r\n			<td>400 N</td>\r\n			<td>\r\n			<div class="choice">d.</div>\r\n			</td>\r\n			<td>1000 N</td>\r\n		</tr>\r\n		<tr>\r\n			<td>\r\n			<div class="choice">b.</div>\r\n			</td>\r\n			<td>500 N</td>\r\n			<td>\r\n			<div class="choice">e.</div>\r\n			</td>\r\n			<td>2000 N</td>\r\n		</tr>\r\n		<tr>\r\n			<td>\r\n			<div class="choice">c.</div>\r\n			</td>\r\n			<td>320 N</td>\r\n		</tr>\r\n	</tbody>\r\n</table>\r\n</div>\r\n'),
(8, 0, '<table align="left" border="0" cellpadding="0" cellspacing="0" style="width:100%">\r\n	<tbody>\r\n		<tr>\r\n			<td>\r\n			<p>&nbsp;</p>\r\n			</td>\r\n			<td>\r\n			<div class="default">Galaksi yang kita humi saat ini adalah? &hellip;</div>\r\n\r\n			<div class="default">\r\n			<table border="0" cellpadding="0" cellspacing="0" style="width:95%">\r\n				<tbody>\r\n					<tr>\r\n						<td>\r\n						<div class="choice">a.</div>\r\n						</td>\r\n						<td>Galaksi Andromeda</td>\r\n						<td>\r\n						<div class="choice">d.</div>\r\n						</td>\r\n						<td>Galaksi Cepheid</td>\r\n					</tr>\r\n					<tr>\r\n						<td>\r\n						<div class="choice">b.</div>\r\n						</td>\r\n						<td>Galaksi Bimasakti</td>\r\n						<td>\r\n						<div class="choice">e.</div>\r\n						</td>\r\n						<td>Galaksi Rozen</td>\r\n					</tr>\r\n					<tr>\r\n						<td>\r\n						<div class="choice">c.</div>\r\n						</td>\r\n						<td>Galaksi Arcturus</td>\r\n					</tr>\r\n				</tbody>\r\n			</table>\r\n			</div>\r\n			</td>\r\n		</tr>\r\n	</tbody>\r\n</table>\r\n'),
(9, 0, '<div class="default">Sebuah pesawat bomber tipe Muttan sedang terbang mendatar dengan kecepatan 200 m/s dan ketinggian 500 m. Pesawat itu diberi misi untuk menjatuhkan bom ke suatu sasaran. Jika ia ingin mengenai sasarannya, berapa jarak antara titik saat pesawat menjatuhkan bom dan titik sasaran bom?</div>\r\n\r\n<div class="default">\r\n<table border="0" cellpadding="0" cellspacing="0" style="width:95%">\r\n	<tbody>\r\n		<tr>\r\n			<td>\r\n			<div class="choice">a.</div>\r\n			</td>\r\n			<td>500 m</td>\r\n			<td>\r\n			<div class="choice">d.</div>\r\n			</td>\r\n			<td>1750 m</td>\r\n		</tr>\r\n		<tr>\r\n			<td>\r\n			<div class="choice">b.</div>\r\n			</td>\r\n			<td>1000 m</td>\r\n			<td>\r\n			<div class="choice">e.</div>\r\n			</td>\r\n			<td>2000 m</td>\r\n		</tr>\r\n		<tr>\r\n			<td>\r\n			<div class="choice">c.</div>\r\n			</td>\r\n			<td>1500 m</td>\r\n		</tr>\r\n	</tbody>\r\n</table>\r\n</div>\r\n'),
(10, 0, '<div class="default">Sebuah cermin cembung berjari-jari 16 cm. Jika jarak bayangan ke cermin 6 cm, maka jarak benda ke lensa adalah &hellip;</div>\r\n\r\n<div class="default">\r\n<table border="0" cellpadding="0" cellspacing="0" style="width:95%">\r\n	<tbody>\r\n		<tr>\r\n			<td>\r\n			<div class="choice">a.</div>\r\n			</td>\r\n			<td>-24 cm</td>\r\n			<td>\r\n			<div class="choice">d.</div>\r\n			</td>\r\n			<td>12 cm</td>\r\n		</tr>\r\n		<tr>\r\n			<td>\r\n			<div class="choice">b.</div>\r\n			</td>\r\n			<td>-12 cm</td>\r\n			<td>\r\n			<div class="choice">e.</div>\r\n			</td>\r\n			<td>24 cm</td>\r\n		</tr>\r\n		<tr>\r\n			<td>\r\n			<div class="choice">c.</div>\r\n			</td>\r\n			<td>&nbsp;&nbsp;&nbsp; 8 cm</td>\r\n		</tr>\r\n	</tbody>\r\n</table>\r\n</div>\r\n'),
(11, 0, '<div class="default">Titik dekat seseorang 2 m. ia ingin membaca buku dengan jarak 25 cm. maka kekuatan kacamatanya adalah? &hellip;</div>\r\n\r\n<div class="default">\r\n<table border="0" cellpadding="0" cellspacing="0" style="width:95%">\r\n	<tbody>\r\n		<tr>\r\n			<td>\r\n			<div class="choice">a.</div>\r\n			</td>\r\n			<td>-3,5 dioptri</td>\r\n			<td>\r\n			<div class="choice">d.</div>\r\n			</td>\r\n			<td>-3 dioptri</td>\r\n		</tr>\r\n		<tr>\r\n			<td>\r\n			<div class="choice">b.</div>\r\n			</td>\r\n			<td>3,5 dioptri</td>\r\n			<td>\r\n			<div class="choice">e.</div>\r\n			</td>\r\n			<td>tidak perlu menggunakan kacamata</td>\r\n		</tr>\r\n		<tr>\r\n			<td>\r\n			<div class="choice">c.</div>\r\n			</td>\r\n			<td>3 dioptri</td>\r\n		</tr>\r\n	</tbody>\r\n</table>\r\n</div>\r\n'),
(12, 0, '<table align="left" border="0" cellpadding="0" cellspacing="0" style="width:100%">\r\n	<tbody>\r\n		<tr>\r\n			<td>\r\n			<p>&nbsp;</p>\r\n			</td>\r\n			<td>\r\n			<div class="default">Sebuah lampu tertulis 25 w, 220 V. maka hambatan lampu itu adalah? &hellip;</div>\r\n\r\n			<div class="default">\r\n			<table border="0" cellpadding="0" cellspacing="0" style="width:95%">\r\n				<tbody>\r\n					<tr>\r\n						<td>\r\n						<div class="choice">a.</div>\r\n						</td>\r\n						<td>8 ohm</td>\r\n						<td>\r\n						<div class="choice">d.</div>\r\n						</td>\r\n						<td>1936 ohm</td>\r\n					</tr>\r\n					<tr>\r\n						<td>\r\n						<div class="choice">b.</div>\r\n						</td>\r\n						<td>625 ohm</td>\r\n						<td>\r\n						<div class="choice">e.</div>\r\n						</td>\r\n						<td>2200 ohm</td>\r\n					</tr>\r\n					<tr>\r\n						<td>\r\n						<div class="choice">c.</div>\r\n						</td>\r\n						<td>1250 ohm</td>\r\n					</tr>\r\n				</tbody>\r\n			</table>\r\n			</div>\r\n			</td>\r\n		</tr>\r\n	</tbody>\r\n</table>\r\n'),
(13, 0, '<div class="default">We ______ because our parents couldn&rsquo;t send us to school. The appropriate word to fill the blank is? &hellip;</div>\r\n\r\n<div class="default">\r\n<table border="0" cellpadding="0" cellspacing="0" style="width:95%">\r\n	<tbody>\r\n		<tr>\r\n			<td>\r\n			<div class="choice">a.</div>\r\n			</td>\r\n			<td>Sent off</td>\r\n			<td>\r\n			<div class="choice">d.</div>\r\n			</td>\r\n			<td>Pulled up</td>\r\n		</tr>\r\n		<tr>\r\n			<td>\r\n			<div class="choice">b.</div>\r\n			</td>\r\n			<td>Paid off</td>\r\n			<td>\r\n			<div class="choice">e.</div>\r\n			</td>\r\n			<td>Lost out</td>\r\n		</tr>\r\n		<tr>\r\n			<td>\r\n			<div class="choice">c.</div>\r\n			</td>\r\n			<td>Pulled off</td>\r\n		</tr>\r\n	</tbody>\r\n</table>\r\n</div>\r\n'),
(14, 0, 'aku adalah itu adalah â–º\r\n'),
(15, 0, '<p>Respiration in green plants occur at . . .<br />\r\nA. Day only<br />\r\nB. Night only<br />\r\nC. Day and night only<br />\r\nD. Together with photosysthesis<br />\r\nE. When light is present</p>\r\n'),
(16, 0, '<p>Pada batang tumbuhan dikotil, jaringan yang berbatasan langsung dengan korteks adalah . . .<br />\r\n<em>A. Primary phloem<br />\r\nB. Secondary phloem<br />\r\nC. Tertiary phloem<br />\r\nD. Secondary xylem<br />\r\nE. Primary xylem</em></p>\r\n'),
(17, 0, 'Mengapa atmosfer bumi berwarna biru?<br />\r\nA. Atmosfer hanya menyerap warna biru<br />\r\nB. Atmosfer memantulkan cahaya biru<br />\r\nC. Atom penyusun atmosfer berwarna biru<br />\r\nD. Karena Bumi sebagian besar terdiri atas laut<br />\r\nE. Tidak ada jawaban yang benar'),
(18, 0, '<p>Sebuah teropong bintang mempunyai lensa objektif dan okuler yang berjarak 105 cm satu sama lain. Teropong tersebut diarahkan pada dua bintang. Mata melihat bayangan bintang jika berakomodasi pada jarak 30 cm. Kemudian lensa okuler digeser 2 cm keluar sehingga pada layar yang diletakkan 42 cm dibelakang okuler terbentuk bayangan. Hitung jarak fokus lensa objektif dan okuler!<br />\r\nA. 100 cm dan 6 cm<br />\r\nB. 6 cm dan 100 cm<br />\r\nC. 112 cm dan 8,4 cm<br />\r\nD. 112 cm dan 6 cm<br />\r\nE. tidak ada jawaban yang benar</p>\r\n'),
(19, 0, '<p><img alt="" src="https://irenerifdah.files.wordpress.com/2012/04/saturn2.jpg" style="height:142px; width:175px" /></p>\r\n\r\n<p>Diatas adalah planet<br />\r\nA. Merkurius<br />\r\nB. Venus<br />\r\nC. Mars<br />\r\nD. Bumi<br />\r\nE. Bulan</p>\r\n'),
(20, 0, '<p><img alt="" src="gambar/a.jpg" /></p>\r\n\r\n<p>A. Kebohongan publik<br />\r\nB. Fakta<br />\r\nC. Sakit<br />\r\nD. Gimana nih fans nya<br />\r\nE. Biasa aja kales</p>\r\n'),
(21, 0, '<p><img src="file:///C:/Users/DELL/AppData/Local/Temp/msohtmlclip1/01/clip_image002.jpg" style="height:154px; width:233px" /></p>\r\n\r\n<p>Kekuatan yang ditunjukkan amperemeter dibawah ini adalah?</p>\r\n\r\n<table border="0" cellpadding="0" cellspacing="0">\r\n	<tbody>\r\n		<tr>\r\n			<td style="width:24px">\r\n			<p>a.</p>\r\n			</td>\r\n			<td style="width:258px">\r\n			<p>70 cA</p>\r\n			</td>\r\n			<td style="width:24px">\r\n			<p>d.</p>\r\n			</td>\r\n			<td style="width:258px">\r\n			<p>3,5 A</p>\r\n			</td>\r\n		</tr>\r\n		<tr>\r\n			<td style="width:24px">\r\n			<p>b.</p>\r\n			</td>\r\n			<td style="width:258px">\r\n			<p>70 mA</p>\r\n			</td>\r\n			<td style="width:24px">\r\n			<p>e.</p>\r\n			</td>\r\n			<td style="width:258px">\r\n			<p>7 A</p>\r\n			</td>\r\n		</tr>\r\n		<tr>\r\n			<td style="width:24px">\r\n			<p>c.</p>\r\n			</td>\r\n			<td style="width:258px">\r\n			<p>0,8 A</p>\r\n			</td>\r\n			<td colspan="2">\r\n			<p>&nbsp;</p>\r\n			</td>\r\n		</tr>\r\n	</tbody>\r\n</table>\r\n');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `tbsoal`
--
ALTER TABLE `tbsoal`
  ADD UNIQUE KEY `indeks` (`indeks`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
